/* ==========================================================================
   RASOI — Base de alimentos
   --------------------------------------------------------------------------
   nome   : nome usual em português
   icone  : (opcional) emoji do próprio alimento — sem ele, herda o da categoria
   cat    : categoria (chave de CATEGORIAS)
   rasa   : sabores predominantes (os 6 rasas)
   virya  : potência térmica — 'quente' (ushna) ou 'frio' (shita)
   gunas  : demais qualidades (a térmica é derivada do virya no código)
   dosha  : efeito sobre cada dosha — -1 pacifica | 0 neutro | +1 agrava
   dica   : orientação prática de preparo e uso
   ========================================================================== */

const ALIMENTOS = [

  /* ---------------------------- GRÃOS E CEREAIS --------------------------- */
  { nome: 'Arroz basmati', icone: '🍚', cat: 'grao', rasa: ['doce'], virya: 'frio', gunas: ['leve','macio','denso'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'O grão mais tridóshico que existe. Lave bem e cozinhe com um fio de ghee e sal.' },
  { nome: 'Arroz integral', icone: '🍚', cat: 'grao', rasa: ['doce'], virya: 'quente', gunas: ['pesado','denso','aspero','estavel'],
    dosha: { vata: -1, pitta: 0, kapha: 1 },
    dica: 'Deixe de molho algumas horas antes de cozinhar para aliviar o peso.' },
  { nome: 'Trigo (pão, massa)', icone: '🍞', cat: 'grao', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','estavel','denso'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Nutritivo e aterrador para Vata, pesado para Kapha. Prefira fermentação longa.' },
  { nome: 'Aveia cozida', icone: '🥣', cat: 'grao', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','macio','viscoso'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Cozida fica cremosa e reconfortante; crua (overnight) fica fria e pesada demais.' },
  { nome: 'Cevada', cat: 'grao', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Diurético clássico do Ayurveda. Excelente contra retenção de líquido e peso.' },
  { nome: 'Milho', icone: '🌽', cat: 'grao', rasa: ['doce'], virya: 'quente', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: 1, kapha: -1 },
    dica: 'Seca e aquece ao mesmo tempo: ótimo no frio úmido, ruim na secura.' },
  { nome: 'Quinoa', cat: 'grao', rasa: ['doce','adstringente'], virya: 'quente', gunas: ['leve','seco'],
    dosha: { vata: 0, pitta: 0, kapha: -1 },
    dica: 'Lave para remover a saponina. Leve e proteica, muito boa para Kapha.' },
  { nome: 'Painço (millet)', cat: 'grao', rasa: ['doce','adstringente'], virya: 'quente', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: 1, kapha: -1 },
    dica: 'Muito secante e aquecedor: o grão de eleição para Kapha no inverno chuvoso.' },
  { nome: 'Trigo-sarraceno', cat: 'grao', rasa: ['doce','adstringente'], virya: 'quente', gunas: ['leve','seco'],
    dosha: { vata: 1, pitta: 1, kapha: -1 },
    dica: 'Aquece bastante. Use no frio; evite em quadros de calor interno.' },
  { nome: 'Amaranto', cat: 'grao', rasa: ['doce','adstringente'], virya: 'quente', gunas: ['leve','seco'],
    dosha: { vata: 0, pitta: 0, kapha: -1 },
    dica: 'Leve e mineralizante. Pede especiarias digestivas para não ressecar.' },
  { nome: 'Centeio', cat: 'grao', rasa: ['adstringente','doce'], virya: 'quente', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: 0, kapha: -1 },
    dica: 'Enxuga a umidade excessiva do corpo. Áspero para intestinos sensíveis.' },
  { nome: 'Tapioca / polvilho', cat: 'grao', rasa: ['doce'], virya: 'frio', gunas: ['pesado','macio','denso','estavel'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Acalma e refresca. Sempre com recheio oleoso e especiarias para não empedrar.' },
  { nome: 'Semolina / cuscuz', cat: 'grao', rasa: ['doce'], virya: 'frio', gunas: ['pesado','macio','denso'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Base do halva ayurvédico. Tostar na manteiga clarificada antes deixa mais leve.' },

  /* ------------------------------ LEGUMINOSAS ----------------------------- */
  { nome: 'Mung dal (feijão mungo)', cat: 'leguminosa', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 0, pitta: -1, kapha: -1 },
    dica: 'A leguminosa mais tridóshica. Base do kitchari, prato de limpeza por excelência.' },
  { nome: 'Lentilha vermelha', cat: 'leguminosa', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 0, pitta: -1, kapha: -1 },
    dica: 'Cozinha rápido e desmancha: a mais leve das lentilhas.' },
  { nome: 'Lentilha marrom', cat: 'leguminosa', rasa: ['adstringente'], virya: 'frio', gunas: ['pesado','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Molho prévio + cominho, hing e gengibre no cozimento evitam os gases.' },
  { nome: 'Grão-de-bico', cat: 'leguminosa', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['pesado','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Seco e pesado. Molho de 12 horas e especiarias carminativas são obrigatórios.' },
  { nome: 'Feijão preto', cat: 'leguminosa', rasa: ['adstringente','doce'], virya: 'frio', gunas: ['pesado','seco','denso'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'O mais pesado do grupo. Descarte a água do molho e use bastante especiaria quente.' },
  { nome: 'Feijão azuki', cat: 'leguminosa', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 0, pitta: -1, kapha: -1 },
    dica: 'Diurético e leve: o feijão escuro mais amigável para a digestão.' },
  { nome: 'Feijão branco', cat: 'leguminosa', rasa: ['adstringente'], virya: 'frio', gunas: ['pesado','seco'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Refrescante no calor; evite na estação seca e ventosa.' },
  { nome: 'Ervilha seca', icone: '🫛', cat: 'leguminosa', rasa: ['adstringente','doce'], virya: 'frio', gunas: ['seco','leve','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Muito adstringente. Cozinhe até virar creme e finalize com ghee.' },
  { nome: 'Urad dal (feijão preto indiano)', cat: 'leguminosa', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','viscoso','denso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Fortificante e reconstrutor. Ótimo para Vata debilitado, pesado demais para Kapha.' },
  { nome: 'Tofu', cat: 'leguminosa', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['pesado','macio','oleoso','denso'],
    dosha: { vata: 1, pitta: -1, kapha: 1 },
    dica: 'Frio e pesado: sirva grelhado ou refogado com gengibre e especiarias quentes.' },
  { nome: 'Soja (grão)', cat: 'leguminosa', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','denso'],
    dosha: { vata: 1, pitta: -1, kapha: 1 },
    dica: 'De difícil digestão. Prefira as versões fermentadas, como missô e tempeh.' },
  { nome: 'Ervilha fresca', icone: '🫛', cat: 'leguminosa', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Leve e refrescante. Amasse ou faça purê para reduzir o efeito ressecante.' },

  /* ------------------------------- VEGETAIS ------------------------------- */
  { nome: 'Abóbora / moranga', icone: '🎃', cat: 'vegetal', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','macio','liquido'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Doce, macia e hidratante: um bálsamo em climas quentes e secos.' },
  { nome: 'Abobrinha', cat: 'vegetal', rasa: ['doce'], virya: 'frio', gunas: ['leve','liquido','macio'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Um dos vegetais mais equilibrados de todos. Refogue com cominho.' },
  { nome: 'Cenoura cozida', icone: '🥕', cat: 'vegetal', rasa: ['doce','amargo'], virya: 'quente', gunas: ['leve','macio'],
    dosha: { vata: -1, pitta: 0, kapha: -1 },
    dica: 'Cozida acalma Vata; crua em excesso aquece Pitta.' },
  { nome: 'Beterraba', cat: 'vegetal', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','macio'],
    dosha: { vata: -1, pitta: 1, kapha: 0 },
    dica: 'Aquece o sangue e nutre em profundidade. Excelente no frio, moderar no calor.' },
  { nome: 'Batata-doce', icone: '🍠', cat: 'vegetal', rasa: ['doce'], virya: 'frio', gunas: ['pesado','macio','denso','estavel'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Aterradora e nutritiva. Assada com ghee e canela fica perfeita para Vata.' },
  { nome: 'Batata inglesa', icone: '🥔', cat: 'vegetal', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['seco','leve','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Parece pesada, mas é seca e forma gases. Use gordura e especiaria em abundância.' },
  { nome: 'Espinafre', cat: 'vegetal', rasa: ['adstringente','amargo'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Refrescante e depurativo. Sempre refogado, nunca cru em grande quantidade.' },
  { nome: 'Couve', cat: 'vegetal', rasa: ['amargo','adstringente'], virya: 'frio', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Limpa e aligeira. Refogada no ghee com alho não agrava tanto Vata.' },
  { nome: 'Brócolis', icone: '🥦', cat: 'vegetal', rasa: ['adstringente','amargo'], virya: 'frio', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'No vapor, com azeite e limão, fica muito mais digerível.' },
  { nome: 'Repolho', cat: 'vegetal', rasa: ['adstringente'], virya: 'frio', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Forma gases quando cru. Refogue com cominho e sementes de mostarda.' },
  { nome: 'Couve-flor', cat: 'vegetal', rasa: ['adstringente'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Leve e seca: ideal para Kapha, difícil para Vata.' },
  { nome: 'Berinjela', icone: '🍆', cat: 'vegetal', rasa: ['adstringente','picante'], virya: 'quente', gunas: ['leve','seco','penetrante'],
    dosha: { vata: 0, pitta: 1, kapha: -1 },
    dica: 'Aquece e seca. Assada com azeite fica bem mais equilibrada.' },
  { nome: 'Tomate cozido', icone: '🍅', cat: 'vegetal', rasa: ['acido','doce'], virya: 'quente', gunas: ['leve','liquido','penetrante'],
    dosha: { vata: 0, pitta: 1, kapha: 0 },
    dica: 'Cru é ácido e agrava Pitta; cozido com especiarias fica bem mais amistoso.' },
  { nome: 'Pepino', icone: '🥒', cat: 'vegetal', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['liquido','macio','pesado'],
    dosha: { vata: 0, pitta: -1, kapha: 1 },
    dica: 'O refrescante clássico do calor seco. Evite no frio úmido.' },
  { nome: 'Alface', cat: 'vegetal', rasa: ['adstringente','amargo'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Refresca sem pesar. Regue com azeite para não ressecar demais.' },
  { nome: 'Aipo / salsão', cat: 'vegetal', rasa: ['adstringente','amargo'], virya: 'frio', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Diurético e desintoxicante, mas muito seco para quem já está ressecado.' },
  { nome: 'Quiabo', cat: 'vegetal', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['viscoso','macio','pesado'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'A mucilagem lubrifica os canais: ótimo contra secura interna e articulações rígidas.' },
  { nome: 'Cebola cozida', icone: '🧅', cat: 'vegetal', rasa: ['doce','picante'], virya: 'quente', gunas: ['pesado','macio','oleoso'],
    dosha: { vata: -1, pitta: 1, kapha: 0 },
    dica: 'Cozida fica doce e nutritiva; crua é picante e muito estimulante.' },
  { nome: 'Alho', icone: '🧄', cat: 'vegetal', rasa: ['picante'], virya: 'quente', gunas: ['oleoso','penetrante','pesado','sutil'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Aquecedor potente e um dos melhores remédios para o frio úmido.' },
  { nome: 'Rabanete', cat: 'vegetal', rasa: ['picante'], virya: 'quente', gunas: ['leve','penetrante','seco'],
    dosha: { vata: 0, pitta: 1, kapha: -1 },
    dica: 'Desobstrui e raspa o muco. Cru é ainda mais penetrante que cozido.' },
  { nome: 'Chuchu', cat: 'vegetal', rasa: ['doce'], virya: 'frio', gunas: ['leve','liquido','macio'],
    dosha: { vata: 0, pitta: -1, kapha: 0 },
    dica: 'Neutro e hidratante, fácil para praticamente todo mundo.' },
  { nome: 'Vagem', cat: 'vegetal', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 0, pitta: -1, kapha: -1 },
    dica: 'Bem cozida e com ghee, é o verde mais fácil do grupo das leguminosas.' },
  { nome: 'Aspargos', cat: 'vegetal', rasa: ['doce','amargo','adstringente'], virya: 'frio', gunas: ['leve','oleoso','macio'],
    dosha: { vata: -1, pitta: -1, kapha: -1 },
    dica: 'Raro caso de vegetal tridóshico: leve sem ser ressecante.' },
  { nome: 'Nabo', cat: 'vegetal', rasa: ['picante','adstringente'], virya: 'quente', gunas: ['leve','seco','penetrante'],
    dosha: { vata: 1, pitta: 1, kapha: -1 },
    dica: 'Raspa o excesso de umidade. Prato de dia frio e chuvoso.' },
  { nome: 'Mandioca / aipim', cat: 'vegetal', rasa: ['doce'], virya: 'frio', gunas: ['pesado','denso','macio','estavel'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Muito aterradora. Sempre com gordura e especiarias digestivas.' },
  { nome: 'Pimentão', icone: '🫑', cat: 'vegetal', rasa: ['picante','doce'], virya: 'quente', gunas: ['leve','penetrante'],
    dosha: { vata: 0, pitta: 1, kapha: -1 },
    dica: 'Aquece e estimula. Assado perde parte do ardor.' },
  { nome: 'Folhas amargas (rúcula, almeirão)', cat: 'vegetal', rasa: ['amargo'], virya: 'frio', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Depurativas do fígado. O amargo é o sabor que mais reduz Kapha e Pitta.' },
  { nome: 'Milho verde na espiga', icone: '🌽', cat: 'vegetal', rasa: ['doce'], virya: 'quente', gunas: ['leve','seco'],
    dosha: { vata: 1, pitta: 0, kapha: -1 },
    dica: 'Passe manteiga ou ghee para compensar a secura do grão.' },

  /* -------------------------------- FRUTAS -------------------------------- */
  { nome: 'Banana madura', icone: '🍌', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','macio','viscoso'],
    dosha: { vata: -1, pitta: 0, kapha: 1 },
    dica: 'Muito aterradora. Com cardamomo fica mais digerível. Nunca com leite.' },
  { nome: 'Manga madura', icone: '🥭', cat: 'fruta', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','macio'],
    dosha: { vata: -1, pitta: 0, kapha: 1 },
    dica: 'Reconstrutora de tecidos. A verde é ácida e agrava Pitta com facilidade.' },
  { nome: 'Maçã crua', icone: '🍏', cat: 'fruta', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['leve','seco','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Crua agrava Vata; cozida com cravo e canela vira alimento aquecedor e macio.' },
  { nome: 'Maçã cozida com especiarias', icone: '🍎', cat: 'fruta', rasa: ['doce'], virya: 'quente', gunas: ['macio','oleoso','pesado'],
    dosha: { vata: -1, pitta: 0, kapha: 0 },
    dica: 'Café da manhã ayurvédico por excelência em dias frios e secos.' },
  { nome: 'Pera', icone: '🍐', cat: 'fruta', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 1, pitta: -1, kapha: -1 },
    dica: 'Adstringente e refrescante. Boa para Kapha e Pitta, seca para Vata.' },
  { nome: 'Uva', icone: '🍇', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['liquido','macio','oleoso'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Uma das frutas mais tridóshicas. Refresca sem ressecar.' },
  { nome: 'Melancia', icone: '🍉', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['pesado','liquido'],
    dosha: { vata: 0, pitta: -1, kapha: 1 },
    dica: 'Coma sozinha, longe das refeições. Uma pitada de sal e limão ajuda a digerir.' },
  { nome: 'Melão', icone: '🍈', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['pesado','liquido','oleoso'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Hidratação profunda no calor seco. Nunca combine com outros alimentos.' },
  { nome: 'Abacate', icone: '🥑', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','macio','denso'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Gordura refrescante: das melhores coisas para Pitta em dias quentes.' },
  { nome: 'Coco fresco', icone: '🥥', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','macio'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Refrigerante e nutritivo ao mesmo tempo — raro e precioso no calor seco.' },
  { nome: 'Água de coco', icone: '🥥', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['liquido','leve','claro'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Repositor natural. Beba em temperatura ambiente, nunca gelada.' },
  { nome: 'Limão', icone: '🍋', cat: 'fruta', rasa: ['acido'], virya: 'quente', gunas: ['leve','liquido','penetrante'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Acende o agni. Água morna com limão pela manhã é clássico para Kapha.' },
  { nome: 'Laranja', icone: '🍊', cat: 'fruta', rasa: ['doce','acido'], virya: 'quente', gunas: ['liquido','pesado'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'A doce acalma Vata; a ácida aquece Pitta e aumenta muco em Kapha.' },
  { nome: 'Abacaxi', icone: '🍍', cat: 'fruta', rasa: ['doce','acido'], virya: 'quente', gunas: ['leve','liquido','penetrante'],
    dosha: { vata: -1, pitta: 1, kapha: 0 },
    dica: 'Enzimas digestivas potentes. Uma pitada de pimenta-preta potencializa.' },
  { nome: 'Mamão', cat: 'fruta', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','macio'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Aquece e move o intestino. Ótimo pela manhã em climas frios.' },
  { nome: 'Romã', cat: 'fruta', rasa: ['adstringente','doce'], virya: 'frio', gunas: ['leve','seco'],
    dosha: { vata: 0, pitta: -1, kapha: -1 },
    dica: 'Adstringente que não agrava muito Vata. Excelente para o sangue e para Pitta.' },
  { nome: 'Tâmara', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','macio','denso'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Reconstrutora e energética. Demolhe e cozinhe no leite para máximo efeito.' },
  { nome: 'Figo', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['pesado','macio','liquido'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Laxativo suave e nutritivo. Demolhado à noite, comido pela manhã.' },
  { nome: 'Uva-passa demolhada', cat: 'fruta', rasa: ['doce'], virya: 'frio', gunas: ['pesado','macio','liquido'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Seca agrava Vata; demolhada em água por 8h vira alimento umectante.' },
  { nome: 'Ameixa seca demolhada', cat: 'fruta', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['pesado','macio','liquido'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Amolece as fezes sem irritar. Deixe de molho na noite anterior.' },
  { nome: 'Morango', icone: '🍓', cat: 'fruta', rasa: ['doce','acido'], virya: 'quente', gunas: ['leve','liquido'],
    dosha: { vata: -1, pitta: 1, kapha: 0 },
    dica: 'Levemente ácido. Em excesso aquece o sangue e irrita a pele de Pitta.' },
  { nome: 'Cereja', icone: '🍒', cat: 'fruta', rasa: ['doce','acido'], virya: 'quente', gunas: ['leve'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Aquecedora e leve. Boa fruta de transição no fim do inverno.' },
  { nome: 'Goiaba', cat: 'fruta', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['pesado','aspero'],
    dosha: { vata: 1, pitta: -1, kapha: 0 },
    dica: 'Muito adstringente pelas sementes. Prefira a polpa bem madura.' },
  { nome: 'Caqui', cat: 'fruta', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['pesado','macio'],
    dosha: { vata: 0, pitta: -1, kapha: 1 },
    dica: 'Só quando muito maduro — verde, a adstringência é agressiva.' },

  /* ------------------------------ LATICÍNIOS ------------------------------ */
  { nome: 'Leite morno com especiarias', cat: 'laticinio', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','liquido','macio'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Nunca gelado e nunca com sal, frutas ou carne. Ferva com cardamomo e gengibre.' },
  { nome: 'Ghee (manteiga clarificada)', icone: '🧈', cat: 'laticinio', rasa: ['doce'], virya: 'frio', gunas: ['oleoso','pesado','macio','sutil'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'A gordura mais reverenciada do Ayurveda: carrega as ervas até os tecidos profundos.' },
  { nome: 'Manteiga', icone: '🧈', cat: 'laticinio', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','macio'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Sem sal é melhor. Mais pesada que o ghee por conter sólidos do leite.' },
  { nome: 'Iogurte natural', cat: 'laticinio', rasa: ['acido','doce'], virya: 'quente', gunas: ['pesado','oleoso','viscoso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Ao contrário do senso comum, esquenta e forma muco. Nunca à noite, nunca gelado.' },
  { nome: 'Lassi (iogurte batido com água)', icone: '🥤', cat: 'laticinio', rasa: ['acido','doce','adstringente'], virya: 'frio', gunas: ['leve','liquido','claro'],
    dosha: { vata: -1, pitta: 0, kapha: -1 },
    dica: 'Diluir o iogurte inverte suas qualidades: fica leve e digestivo. O melhor pós-almoço.' },
  { nome: 'Queijo fresco / paneer', icone: '🧀', cat: 'laticinio', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','denso','macio'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Feito na hora e temperado com pimenta-preta, é o queijo mais digerível.' },
  { nome: 'Queijo curado', icone: '🧀', cat: 'laticinio', rasa: ['doce','acido','salgado'], virya: 'quente', gunas: ['pesado','oleoso','denso','estavel'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Muito pesado e obstruinte. Pequenas porções, sempre com especiarias picantes.' },
  { nome: 'Creme de leite', cat: 'laticinio', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','viscoso','denso'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Extremamente untuoso. Reservado para quadros de secura e desgaste.' },

  /* ------------------------ OLEAGINOSAS E SEMENTES ------------------------ */
  { nome: 'Amêndoa demolhada e sem pele', cat: 'oleaginosa', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','macio'],
    dosha: { vata: -1, pitta: 0, kapha: 1 },
    dica: 'Demolhar 8h e retirar a pele é o que a torna sátvica e digerível.' },
  { nome: 'Castanha-de-caju', cat: 'oleaginosa', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','macio'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Cremosa e nutritiva. Ótima base de molhos para quem não come laticínio.' },
  { nome: 'Noz', cat: 'oleaginosa', rasa: ['doce','adstringente'], virya: 'quente', gunas: ['pesado','oleoso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Aquecedora e lubrificante: alimento de inverno para Vata.' },
  { nome: 'Gergelim', cat: 'oleaginosa', rasa: ['doce','amargo'], virya: 'quente', gunas: ['pesado','oleoso','penetrante'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'A semente mais aquecedora. Base do tahine e do óleo de massagem ayurvédico.' },
  { nome: 'Semente de girassol', icone: '🌻', cat: 'oleaginosa', rasa: ['doce'], virya: 'frio', gunas: ['oleoso','pesado'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Oleosa sem aquecer: uma das poucas sementes boas para Pitta.' },
  { nome: 'Semente de abóbora', cat: 'oleaginosa', rasa: ['doce','adstringente'], virya: 'quente', gunas: ['oleoso','pesado'],
    dosha: { vata: -1, pitta: 0, kapha: 0 },
    dica: 'Levemente tostadas com sal, são um ótimo lanche aterrador.' },
  { nome: 'Linhaça', cat: 'oleaginosa', rasa: ['doce'], virya: 'quente', gunas: ['oleoso','pesado','viscoso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Moída na hora e com água morna, é laxativo suave para Vata.' },
  { nome: 'Chia', cat: 'oleaginosa', rasa: ['doce','adstringente'], virya: 'frio', gunas: ['oleoso','viscoso','pesado'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Hidratada forma gel que lubrifica os intestinos. Seca, resseca — sempre demolhe.' },
  { nome: 'Amendoim', icone: '🥜', cat: 'oleaginosa', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','denso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'O mais pesado do grupo e o que mais forma ama. Consumo moderado.' },
  { nome: 'Pistache', cat: 'oleaginosa', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Aquecedor e reconstrutor. Bom em pequenas quantidades no frio.' },

  /* --------------------------- ÓLEOS E GORDURAS --------------------------- */
  { nome: 'Óleo de gergelim', cat: 'oleo', rasa: ['doce','amargo','adstringente'], virya: 'quente', gunas: ['oleoso','pesado','penetrante','estavel'],
    dosha: { vata: -1, pitta: 1, kapha: 0 },
    dica: 'O óleo por excelência de Vata. Aquece, penetra e estabiliza — na comida e na pele.' },
  { nome: 'Óleo de coco', icone: '🥥', cat: 'oleo', rasa: ['doce'], virya: 'frio', gunas: ['oleoso','pesado','macio'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'O óleo refrescante: primeira escolha para Pitta e para o verão.' },
  { nome: 'Azeite de oliva', cat: 'oleo', rasa: ['doce'], virya: 'frio', gunas: ['oleoso','pesado','macio'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Suave e neutro. Melhor cru, regado sobre o prato pronto.' },
  { nome: 'Óleo de mostarda', cat: 'oleo', rasa: ['picante'], virya: 'quente', gunas: ['oleoso','penetrante','leve','sutil'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Muito aquecedor e desobstruinte: o óleo de Kapha no inverno chuvoso.' },
  { nome: 'Óleo de girassol', icone: '🌻', cat: 'oleo', rasa: ['doce'], virya: 'frio', gunas: ['oleoso','leve'],
    dosha: { vata: -1, pitta: -1, kapha: 0 },
    dica: 'Leve e refrescante, uma alternativa quando o ghee pesa demais.' },

  /* -------------------------- ESPECIARIAS E ERVAS ------------------------- */
  { nome: 'Gengibre fresco', icone: '🫚', cat: 'especiaria', rasa: ['picante'], virya: 'quente', gunas: ['liquido','penetrante','leve'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'O remédio universal. Fatias com limão e sal antes da refeição acendem o agni.' },
  { nome: 'Gengibre seco (sonth)', icone: '🫚', cat: 'especiaria', rasa: ['picante'], virya: 'quente', gunas: ['seco','leve','penetrante'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Mais quente e mais secante que o fresco. Ideal para umidade e muco.' },
  { nome: 'Cúrcuma', cat: 'especiaria', rasa: ['amargo','picante','adstringente'], virya: 'quente', gunas: ['seco','leve','aspero'],
    dosha: { vata: 0, pitta: 0, kapha: -1 },
    dica: 'Tridóshica em pequenas doses. Precisa de gordura e pimenta-preta para absorver.' },
  { nome: 'Cominho', cat: 'especiaria', rasa: ['picante','amargo'], virya: 'quente', gunas: ['leve','seco','penetrante'],
    dosha: { vata: -1, pitta: 0, kapha: -1 },
    dica: 'A especiaria digestiva mais versátil. Toste as sementes no ghee antes de tudo.' },
  { nome: 'Coentro (semente)', cat: 'especiaria', rasa: ['doce','amargo','adstringente'], virya: 'frio', gunas: ['leve','oleoso'],
    dosha: { vata: -1, pitta: -1, kapha: -1 },
    dica: 'Refresca sem apagar o agni: a especiaria preferida de Pitta.' },
  { nome: 'Erva-doce / funcho', cat: 'especiaria', rasa: ['doce','picante','amargo'], virya: 'frio', gunas: ['leve','oleoso'],
    dosha: { vata: -1, pitta: -1, kapha: -1 },
    dica: 'Tridóshica. Mastigar as sementes depois da refeição melhora a digestão e o hálito.' },
  { nome: 'Cardamomo', cat: 'especiaria', rasa: ['doce','picante'], virya: 'frio', gunas: ['leve','seco','sutil'],
    dosha: { vata: -1, pitta: -1, kapha: -1 },
    dica: 'Neutraliza o efeito formador de muco do leite e do café.' },
  { nome: 'Canela', cat: 'especiaria', rasa: ['doce','picante','amargo'], virya: 'quente', gunas: ['leve','seco','penetrante'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Aquece a circulação periférica. Perfeita em dias frios e úmidos.' },
  { nome: 'Cravo-da-índia', cat: 'especiaria', rasa: ['picante'], virya: 'quente', gunas: ['leve','seco','penetrante','sutil'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Potente descongestionante. Um ou dois cravos bastam em qualquer preparo.' },
  { nome: 'Pimenta-preta', cat: 'especiaria', rasa: ['picante'], virya: 'quente', gunas: ['leve','seco','penetrante'],
    dosha: { vata: 0, pitta: 1, kapha: -1 },
    dica: 'Queima o ama e potencializa a absorção de outras ervas. Moa na hora.' },
  { nome: 'Pimenta caiena / malagueta', icone: '🌶️', cat: 'especiaria', rasa: ['picante'], virya: 'quente', gunas: ['leve','seco','penetrante'],
    dosha: { vata: 1, pitta: 1, kapha: -1 },
    dica: 'A mais intensa. Ótima contra o frio úmido, agressiva para Pitta e Vata.' },
  { nome: 'Asafétida (hing)', cat: 'especiaria', rasa: ['picante'], virya: 'quente', gunas: ['oleoso','penetrante','leve'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Uma pitada no óleo quente elimina os gases das leguminosas. Insubstituível.' },
  { nome: 'Feno-grego', cat: 'especiaria', rasa: ['amargo','picante'], virya: 'quente', gunas: ['seco','leve','penetrante'],
    dosha: { vata: 0, pitta: 1, kapha: -1 },
    dica: 'Amargo aquecedor, raro e útil. Reduz muco sem esfriar.' },
  { nome: 'Mostarda em grão', cat: 'especiaria', rasa: ['picante'], virya: 'quente', gunas: ['oleoso','penetrante','leve'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Estale as sementes no óleo até pipocarem antes de acrescentar o resto.' },
  { nome: 'Hortelã', cat: 'especiaria', rasa: ['picante','amargo'], virya: 'frio', gunas: ['leve','seco','sutil'],
    dosha: { vata: 0, pitta: -1, kapha: -1 },
    dica: 'Picante que resfria — combinação rara. Chá de hortelã acalma o calor interno.' },
  { nome: 'Manjericão sagrado (tulsi)', cat: 'especiaria', rasa: ['picante','amargo'], virya: 'quente', gunas: ['leve','seco','penetrante','sutil'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Erva sagrada para vias respiratórias e clareza mental. Chá diário no frio úmido.' },
  { nome: 'Salsinha', cat: 'especiaria', rasa: ['picante','amargo'], virya: 'quente', gunas: ['leve','seco'],
    dosha: { vata: 0, pitta: 1, kapha: -1 },
    dica: 'Diurética e mineralizante. Adicione crua no final do preparo.' },
  { nome: 'Açafrão (saffron)', cat: 'especiaria', rasa: ['doce','picante','amargo'], virya: 'frio', gunas: ['leve','sutil','oleoso'],
    dosha: { vata: -1, pitta: -1, kapha: -1 },
    dica: 'Tridóshico e sátvico. Poucos fios no leite morno já bastam.' },
  { nome: 'Noz-moscada', cat: 'especiaria', rasa: ['picante','adstringente'], virya: 'quente', gunas: ['pesado','oleoso','estavel'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Sedativa: uma pitada no leite morno à noite ajuda no sono de Vata.' },
  { nome: 'Sal marinho ou rosa', icone: '🧂', cat: 'especiaria', rasa: ['salgado'], virya: 'quente', gunas: ['pesado','oleoso','liquido','penetrante'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Retém água e amolece os tecidos. Ótimo para Vata, restrito para Kapha e Pitta.' },

  /* ------------------------------- ADOÇANTES ------------------------------ */
  { nome: 'Mel cru', cat: 'adocante', rasa: ['doce','adstringente'], virya: 'quente', gunas: ['seco','leve','aspero'],
    dosha: { vata: 0, pitta: 1, kapha: -1 },
    dica: 'O único adoçante que seca e raspa: o preferido de Kapha. Jamais aquecido acima de 40°C.' },
  { nome: 'Rapadura / açúcar mascavo', cat: 'adocante', rasa: ['doce'], virya: 'frio', gunas: ['pesado','oleoso','viscoso'],
    dosha: { vata: -1, pitta: -1, kapha: 1 },
    dica: 'Refrescante e nutritivo, o oposto do mel em qualidades.' },
  { nome: 'Melado de cana', cat: 'adocante', rasa: ['doce'], virya: 'quente', gunas: ['pesado','viscoso','denso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Aquecedor e mineralizante. Muito usado em preparos de inverno.' },
  { nome: 'Xarope de bordo', icone: '🍁', cat: 'adocante', rasa: ['doce'], virya: 'frio', gunas: ['leve','liquido'],
    dosha: { vata: 0, pitta: -1, kapha: 0 },
    dica: 'Mais leve que os demais açúcares: opção razoável para Pitta.' },

  /* --------------------------- PROTEÍNAS ANIMAIS -------------------------- */
  { nome: 'Ovo', icone: '🥚', cat: 'animal', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','denso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'A gema aquece e nutre; a clara é mais leve e menos aquecedora.' },
  { nome: 'Frango', icone: '🍗', cat: 'animal', rasa: ['doce','adstringente'], virya: 'quente', gunas: ['leve','oleoso'],
    dosha: { vata: -1, pitta: 1, kapha: 0 },
    dica: 'A carne mais leve. Cozida em caldo com especiarias é a forma mais digerível.' },
  { nome: 'Peixe', icone: '🐟', cat: 'animal', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','viscoso'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Aquece muito. Nunca combine com leite — incompatibilidade clássica (viruddha).' },
  { nome: 'Carne vermelha', icone: '🥩', cat: 'animal', rasa: ['doce'], virya: 'quente', gunas: ['pesado','oleoso','denso','estavel'],
    dosha: { vata: -1, pitta: 1, kapha: 1 },
    dica: 'Máxima densidade e peso. Reconstrói tecidos, mas é lenta e forma ama facilmente.' },

  /* -------------------------------- BEBIDAS ------------------------------- */
  { nome: 'Água morna', icone: '💧', cat: 'bebida', rasa: [], virya: 'quente', gunas: ['liquido','leve','claro','penetrante'],
    dosha: { vata: -1, pitta: 0, kapha: -1 },
    dica: 'Goles ao longo do dia dissolvem o ama. A bebida mais recomendada do Ayurveda.' },
  { nome: 'Chá de gengibre', icone: '🫚', cat: 'bebida', rasa: ['picante'], virya: 'quente', gunas: ['liquido','leve','penetrante'],
    dosha: { vata: -1, pitta: 1, kapha: -1 },
    dica: 'Antes das refeições, acende o agni; depois, alivia o peso.' },
  { nome: 'Chá CCF (cominho, coentro, erva-doce)', cat: 'bebida', rasa: ['doce','picante','amargo'], virya: 'frio', gunas: ['liquido','leve','claro'],
    dosha: { vata: -1, pitta: -1, kapha: -1 },
    dica: 'O chá tridóshico universal: digestivo e desintoxicante sem desequilibrar ninguém.' },
  { nome: 'Chá de hortelã', cat: 'bebida', rasa: ['picante','amargo'], virya: 'frio', gunas: ['liquido','leve','sutil'],
    dosha: { vata: 0, pitta: -1, kapha: -1 },
    dica: 'Resfria a cabeça e o estômago sem apagar o fogo digestivo.' },
  { nome: 'Leite dourado (golden milk)', icone: '🥛', cat: 'bebida', rasa: ['doce','picante'], virya: 'quente', gunas: ['oleoso','pesado','liquido','macio'],
    dosha: { vata: -1, pitta: 0, kapha: 0 },
    dica: 'Leite fervido com cúrcuma, pimenta e ghee. Bebida noturna de inverno.' },
  { nome: 'Chá preto', icone: '🫖', cat: 'bebida', rasa: ['adstringente','amargo'], virya: 'quente', gunas: ['leve','seco','penetrante','movel'],
    dosha: { vata: 1, pitta: 1, kapha: -1 },
    dica: 'Estimula e seca. Com leite e especiarias (chai masala) fica bem mais equilibrado.' },
  { nome: 'Café', icone: '☕', cat: 'bebida', rasa: ['amargo','adstringente'], virya: 'quente', gunas: ['leve','seco','penetrante','movel'],
    dosha: { vata: 1, pitta: 1, kapha: -1 },
    dica: 'Agita Vata e inflama Pitta. Cardamomo e uma gordura suavizam o impacto.' }

];
